name: Sync Repo using PAT

on:
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: 'The repository to copy from (e.g., rhn/twrp-tree) without github.com'
        required: true
        default: 'nillerusr/source-engine'
      pat:
        description: 'A Personal Access Token (PAT) with full "repo" scope'
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the upstream repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.upstream_repo }}
          path: 'upstream'

      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          path: 'mine'
          token: ${{ github.event.inputs.pat }}

      - name: Copy all files from upstream to your repo
        run: |
          rsync -av --delete upstream/ mine/ --exclude '.git/'

      - name: Commit and push changes
        run: |
          cd mine
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Sync with upstream repository ${{ github.event.inputs.upstream_repo }}"
            git push https://x-access-token:${{ github.event.inputs.pat }}@github.com/${{ github.repository }}.git HEAD:main
            echo "Changes have been synced and pushed to your repository."
          else
            echo "No changes to sync. Your repository is up-to-date."
          fi
