name: Sync Latest Updated Branch with Submodules

on:
  workflow_dispatch:
    inputs:
      upstream_repo:
        description: 'The repository to copy from (e.g., user/repo)'
        required: true
        default: 'nillerusr/source-engine'
      pat:
        description: 'A Personal Access Token (PAT) with "repo" and "workflow" scopes'
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Find the latest updated branch
        id: find_branch
        run: |
          LATEST_BRANCH=$(git ls-remote --heads https://github.com/${{ github.event.inputs.upstream_repo }}.git | \
            sort -k1 -r | \
            head -n 1 | \
            sed 's?.*refs/heads/??')
          
          echo "Latest updated branch is: $LATEST_BRANCH"
          echo "branch_name=$LATEST_BRANCH" >> $GITHUB_OUTPUT

      - name: Checkout latest branch and its submodules
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.upstream_repo }}
          ref: ${{ steps.find_branch.outputs.branch_name }}
          submodules: 'recursive'
          path: 'upstream'
          token: ${{ github.event.inputs.pat }}

      - name: Checkout your repository
        uses: actions/checkout@v4
        with:
          path: 'mine'
          token: ${{ github.event.inputs.pat }}

      # --- التعديل هنا ---
      - name: Clean working directory and Sync new content
        run: |
          # الخطوة 1: تنظيف مستودعك باستخدام git clean (أكثر أمانًا وقوة)
          cd mine
          git clean -fdx
          cd ..
          
          # الخطوة 2: نسخ المحتوى الجديد
          rsync -av upstream/ mine/

      - name: Commit and Force Push to your repository
        run: |
          cd mine
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@github.com"
          
          git add -A
          
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Force sync from latest branch: ${{ steps.find_branch.outputs.branch_name }}"
            git push --force
            echo "Repository has been force-synced with the latest upstream branch."
          else
            echo "No changes to sync."
          fi
