name: Build A15 Kernel - The Final Version

on:
  workflow_dispatch:
    inputs:
      KERNEL_SOURCE_URL:
        description: 'Samsung Kernel Source URL (.zip)'
        required: true
      TOOLCHAIN_URL:
        description: 'AOSP Clang Toolchain URL (.tar.gz)'
        required: true
      STOCK_BOOT_IMG_URL:
        description: 'Stock boot.img URL (Used for Ramdisk)'
        required: true
      YOUR_NAME:
        description: 'Your developer name (no spaces)'
        required: true
        default: 'rhn_1k'

jobs:
  build:
    name: Build and Package Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Download and Prepare Workspace
        id: workspace
        run: |
          # Download and extract Samsung Kernel Source
          curl -L -o source.zip "${{ github.event.inputs.KERNEL_SOURCE_URL }}"
          unzip -q source.zip
          tar -xf Kernel.tar.gz
          
          # Download a PRE-BUILT, RELIABLE magiskboot binary
          mkdir -p tools
          curl -L -o tools/magiskboot "https://github.com/xiaoxindada/magiskboot-aarch64/releases/latest/download/magiskboot"
          chmod +x tools/magiskboot
          
          # Extract Ramdisk from stock boot.img using the pre-built tool
          curl -L -o stock_boot.img "${{ github.event.inputs.STOCK_BOOT_IMG_URL }}"
          ./tools/magiskboot unpack stock_boot.img
          mv ramdisk.cpio ramdisk.cpio.gz
          gzip -d ramdisk.cpio.gz
          lz4 ramdisk.cpio gki-ramdisk.lz4
          
          echo "work_dir=$(realpath .)" >> $GITHUB_OUTPUT

      - name: Setup Toolchain
        run: |
          mkdir -p toolchain
          curl -L "${{ github.event.inputs.TOOLCHAIN_URL }}" | tar -xz -C toolchain --strip-components=1
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CROSS_COMPILE_COMPAT=arm-linux-gnueabi-" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "PATH=$(realpath toolchain/bin):$PATH" >> $GITHUB_ENV

      - name: Configure, Patch, and Integrate
        working-directory: ${{ steps.workspace.outputs.work_dir }}/kernel-5.10
        run: |
          # Recovery Boot Patch
          sed -i 's/if (!cmd)/if (!cmd)\n\t\tcmd = "recovery";\n\telse if (2 < 1)/' drivers/power/reset/reboot-mode.c
          
          # Defconfig modifications
          chmod +x scripts/config
          DEFCONFIG_FILE="arch/arm64/configs/a15_00_defconfig"
          ./scripts/config --file $DEFCONFIG_FILE --set-val UH n --set-val RKP n --set-val KDP n --set-val SECURITY_DEFEX n --set-val INTEGRITY n
          ./scripts/config --file $DEFCONFIG_FILE --set-val KSU y
          
          # Custom Version
          echo "CONFIG_LOCALVERSION=\"-${{ github.event.inputs.YOUR_NAME }}\"" >> $DEFCONFIG_FILE
          echo "CONFIG_LOCALVERSION_AUTO=n" >> $DEFCONFIG_FILE

          # KernelSU Setup
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Build The Kernel (The Correct Method)
        working-directory: ${{ steps.workspace.outputs.work_dir }}
        run: |
          # Generate the main build config
          python2 kernel-5.10/scripts/gen_build_config.py --kernel-defconfig a15_00_defconfig --kernel-defconfig-overlays "entry_level.config" -m user -o out/target/product/a15/obj/KERNEL_OBJ/build.config
          
          # Define the build options to control the build script
          export GKI_KERNEL_BUILD_OPTIONS="
              SKIP_MRPROPER=1
              BUILD_BOOT_IMG=1
              MKBOOTIMG_PATH=$(pwd)/tools/magiskboot
              KERNEL_BINARY=Image.gz
              BOOT_IMAGE_HEADER_VERSION=4
              SKIP_VENDOR_BOOT=1
              GKI_RAMDISK_PREBUILT_BINARY=$(pwd)/gki-ramdisk.lz4
              LTO=thin
          "
          
          # Set the rest of the environment
          export PLATFORM_VERSION=12
          export OUT_DIR="out/target/product/a15/obj/KERNEL_OBJ"
          export DIST_DIR="out/target/product/a15/obj/KERNEL_OBJ"
          export BUILD_CONFIG="out/target/product/a15/obj/KERNEL_OBJ/build.config"
          export MERGE_CONFIG="$(pwd)/kernel-5.10/scripts/kconfig/merge_config.sh"
          
          # Run the build from within the 'kernel' directory, passing the build options
          cd kernel
          env ${GKI_KERNEL_BUILD_OPTIONS} ./build/build.sh

      - name: Upload Final boot.img
        working-directory: ${{ steps.workspace.outputs.work_dir }}
        run: |
          BOOT_IMG_PATH="out/target/product/a15/obj/KERNEL_OBJ/boot.img"
          if [ ! -f "$BOOT_IMG_PATH" ]; then
             echo "Error: boot.img not found!"
             exit 1
          fi
          
          mv $BOOT_IMG_PATH "Patched-boot-A15-${{ github.event.inputs.YOUR_NAME }}.img"
          FILE_PATH=$(realpath "Patched-boot-A15-${{ github.event.inputs.YOUR_NAME }}.img")
          RESPONSE=$(curl -F "file=@${FILE_PATH}" -H "Authorization: Bearer E29ro0ueg1dXX7CHmJSdrO9puOTUMREk" https://upload.gofile.io/uploadFile)
          DOWNLOAD_PAGE=$(echo $RESPONSE | grep -o '"downloadPage": *"[^"]*"' | cut -d '"' -f 4)
          
          if [ -z "$DOWNLOAD_PAGE" ]; then 
            echo "Error: Could not get Gofile URL! Response was:"
            echo $RESPONSE
            exit 1
          fi
          
          echo "----------------------------------------------------------------"
          echo "Build successful. Download your flashable boot.img here: $DOWNLOAD_PAGE"
          echo "----------------------------------------------------------------"
