name: Build A15 Kernel

on:
  workflow_dispatch:
    inputs:
      KERNEL_SOURCE_URL:
        description: 'Direct URL to your RAW Samsung kernel source (.zip)'
        required: true
      TOOLCHAIN_URL:
        description: 'Direct URL to your AOSP Clang toolchain (.tar.gz)'
        required: true
      STOCK_BOOT_IMG_URL:
        description: 'Direct URL to your stock boot.img file'
        required: true
      YOUR_NAME:
        description: 'Your developer name (no spaces)'
        required: true
        default: 'YourName'

jobs:
  build:
    name: Build and Package Kernel
    runs-on: ubuntu-22.04

    steps:
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16

      - name: Install Build Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2
          sudo ln -sf /usr/bin/python2 /usr/bin/python

      - name: Download and Extract Kernel Source
        id: workspace
        run: |
          curl -L -o source.zip "${{ github.event.inputs.KERNEL_SOURCE_URL }}"
          unzip -q source.zip
          KERNEL_ARCHIVE=$(find . -maxdepth 1 -name "*.tar.gz" -o -name "*.tar" | head -n 1)
          if [ -z "$KERNEL_ARCHIVE" ]; then
            echo "Error: Could not find Kernel.tar.gz or similar archive inside the zip."
            exit 1
          fi
          tar -xf "$KERNEL_ARCHIVE"
          
          # THE ABSOLUTE FINAL CRITICAL FIX:
          # The source zip creates TWO folders: 'Kernel' and 'kernel'.
          # 'Kernel' contains the actual kernel source (5.10).
          # 'kernel' contains the build scripts.
          # We need to rename 'Kernel' to 'kernel-5.10' for the patching steps.
          # The 'kernel' folder is already there for the build step.
          if [ -d "Kernel" ]; then
            mv Kernel kernel-5.10
            echo "Renamed 'Kernel' to 'kernel-5.10' for patching."
          else
            echo "Error: The main 'Kernel' source directory was not found."
            exit 1
          fi

          echo "work_dir=$(realpath .)" >> $GITHUB_OUTPUT

      - name: Setup Toolchain
        working-directory: ${{ steps.workspace.outputs.work_dir }}
        run: |
          mkdir -p toolchain
          curl -L "${{ github.event.inputs.TOOLCHAIN_URL }}" | tar -xz -C toolchain --strip-components=1
          echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
          echo "CROSS_COMPILE_COMPAT=arm-linux-gnueabi-" >> $GITHUB_ENV
          echo "CC=clang" >> $GITHUB_ENV
          echo "PATH=$(realpath toolchain/bin):$PATH" >> $GITHUB_ENV

      - name: Configure, Patch, and Integrate
        working-directory: ${{ steps.workspace.outputs.work_dir }}/kernel-5.10
        run: |
          # All commands now run inside the correctly named kernel-5.10 directory.
          
          echo "Modifying configs and applying patches..."
          CONFIG_SCRIPT="scripts/config"
          DEFCONFIG_FILE="arch/arm64/configs/a15_00_defconfig"
          chmod +x $CONFIG_SCRIPT
          
          RECOVERY_PATCH_TARGET="drivers/power/reset/reboot-mode.c"
          if [ -f "$RECOVERY_PATCH_TARGET" ]; then
            sed -i 's/if (!cmd)/if (!cmd)\n\t\tcmd = "recovery";\n\telse if (2 < 1)/' "$RECOVERY_PATCH_TARGET"
            echo "Recovery boot patch applied."
          fi
          
          ./$CONFIG_SCRIPT --file $DEFCONFIG_FILE --set-val UH n --set-val RKP n --set-val KDP n --set-val SECURITY_DEFEX n --set-val INTEGRITY n
          ./$CONFIG_SCRIPT --file $DEFCONFIG_FILE --set-val KSU y
          ./$CONFIG_SCRIPT --file $DEFCONFIG_FILE --set-val SUSFS y

          echo "CONFIG_LOCALVERSION=\"-${{ github.event.inputs.YOUR_NAME }}\"" >> $DEFCONFIG_FILE
          echo "CONFIG_LOCALVERSION_AUTO=n" >> $DEFCONFIG_FILE

          echo "Setting up KernelSU and SuSFS..."
          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/main/kernel/setup.sh" | bash -
          git clone https://github.com/KernelSU-Next/SuSFS.git --depth=1 susfs
          git apply --directory="susfs" --no-index susfs/ksu.patch
          rm -rf susfs

      - name: Build The Kernel (Samsung Official Method for A15)
        working-directory: ${{ steps.workspace.outputs.work_dir }}
        run: |
          python2 kernel-5.10/scripts/gen_build_config.py --kernel-defconfig a15_00_defconfig --kernel-defconfig-overlays "entry_level.config" -m user -o out/target/product/a15/obj/KERNEL_OBJ/build.config
          
          export PLATFORM_VERSION=12
          export OUT_DIR="$(pwd)/out/target/product/a15/obj/KERNEL_OBJ"
          export DIST_DIR="$(pwd)/out/target/product/a15/obj/KERNEL_OBJ"
          export BUILD_CONFIG="$(pwd)/out/target/product/a15/obj/KERNEL_OBJ/build.config"
          
          # The 'kernel' directory (lowercase) is now available from the original extraction.
          cd kernel
          ./build/build.sh

      - name: Repack Boot Image and Upload to Gofile
        working-directory: ${{ steps.workspace.outputs.work_dir }}
        run: |
          git clone https://github.com/topjohnwu/Magisk.git magisk_tools
          curl -L -o stock_boot.img "${{ github.event.inputs.STOCK_BOOT_IMG_URL }}"
          
          magisk_tools/build/tools/magiskboot unpack stock_boot.img
          
          KERNEL_IMAGE="out/target/product/a15/obj/KERNEL_OBJ/arch/arm64/boot/Image.gz"
          if [ ! -f "$KERNEL_IMAGE" ]; then
             echo "Error: Kernel Image.gz not found at the expected path!"
             exit 1
          fi
          cp $KERNEL_IMAGE kernel
          
          magisk_tools/build/tools/magiskboot repack stock_boot.img
          
          mv new-boot.img "Patched-boot-A15-${{ github.event.inputs.YOUR_NAME }}.img"
          
          FILE_PATH=$(realpath "Patched-boot-A15-${{ github.event.inputs.YOUR_NAME }}.img")
          RESPONSE=$(curl -F "file=@${FILE_PATH}" -H "Authorization: Bearer E29ro0ueg1dXX7CHmJSdrO9puOTUMREk" https://upload.gofile.io/uploadFile)
          DOWNLOAD_PAGE=$(echo $RESPONSE | grep -o '"downloadPage": *"[^"]*"' | cut -d '"' -f 4)
          
          if [ -z "$DOWNLOAD_PAGE" ]; then 
            echo "Error: Could not extract download page URL! Response was:"
            echo $RESPONSE
            exit 1
          fi
          
          echo "----------------------------------------------------------------"
          echo "Build successful. Download your flashable boot.img here: $DOWNLOAD_PAGE"
          echo "----------------------------------------------------------------"
