name: Test Repack (Based on Your Script's Logic)

on:
  workflow_dispatch:

jobs:
  test-repack:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y lz4 python3 openssl

      - name: Set Scripts Executable
        run: |
          chmod +x scripts/bin/magiskboot
          chmod +x scripts/bin/avb/avbtool.py

      - name: Patch and Repack (Following YOUR repack.sh logic)
        id: patch_step
        run: |
          echo "--- Starting Test: Following your repack.sh logic ---"
          # Define absolute paths to avoid any 'cd' related errors
          ROOT=$GITHUB_WORKSPACE
          MAGISKBOOT=$ROOT/scripts/bin/magiskboot
          AVBTOOL=$ROOT/scripts/bin/avb/avbtool.py
          BOOT_LZ4=$ROOT/boot.img.lz4
          BOOT_IMG=$ROOT/boot.img
          WORKSPACE=$ROOT/scripts/bin/workspace # Your script uses this specific path for the workspace
          CERTDIR=$ROOT/scripts/bin/certs
          
          # 1. Prepare environment (from your script)
          mkdir -p $WORKSPACE
          rm -rf $WORKSPACE/*
          mkdir -p $CERTDIR
          lz4 -d $BOOT_LZ4 $BOOT_IMG

          # 2. Unpack boot.img into workspace (from your script)
          # Your script changes to workspace, so we will do the same to replicate it exactly
          cd $WORKSPACE
          $MAGISKBOOT unpack -h ../../$BOOT_IMG
          
          # 3. Patch the ramdisk.cpio that is now inside the workspace
          echo "Patching ramdisk.cpio in-place..."
          mkdir -p temp_rc_files
          # Use magiskboot to find, extract, patch, and re-add the rc files
          $MAGISKBOOT cpio ramdisk.cpio "ls" | grep "\.rc$" | while read -r rcfile; do
            echo "Patching file: $rcfile"
            $MAGISKBOOT cpio ramdisk.cpio "extract $rcfile temp_rc_files/$rcfile"
            sed -i 's/setenforce 1/setenforce 0/g' "temp_rc_files/$rcfile"
            PERMS=$($MAGISKBOOT cpio ramdisk.cpio "ls" | grep "$rcfile" | awk '{print $1}')
            $MAGISKBOOT cpio ramdisk.cpio "add $PERMS $rcfile temp_rc_files/$rcfile"
          done
          rm -rf temp_rc_files
          echo "Ramdisk patched successfully."
          
          # 4. Repack the boot image (from your script)
          echo "Repacking boot image..."
          # Your script uses the original boot.img as a template.
          # We are inside WORKSPACE, so the path is ../../boot.img
          # The kernel file is already in the workspace from the unpack step.
          $MAGISKBOOT repack ../../$BOOT_IMG new-boot.img
          
          # 5. Sign the new boot image (from your script)
          echo "Signing new boot image..."
          if [ ! -f "$CERTDIR/sign.pk8" ]; then
            openssl genrsa -out $CERTDIR/sign.pk8 4096
          fi
          
          python3 $AVBTOOL add_hash_footer \
            --partition_name boot \
            --partition_size 67108864 \
            --image new-boot.img \
            --algorithm SHA256_RSA4096 \
            --key $CERTDIR/sign.pk8
          
          # 6. Verify success
          if [ -f "new-boot.img" ]; then
            echo "✅ SUCCESS: 'new-boot.img' was created and signed."
          else
            echo "::error:: Repack failed. 'new-boot.img' was not created."
            exit 1
          fi
          
          # Cleanup
          cd .. # Go back to scripts/bin
          cd .. # Go back to scripts
          cd .. # Go back to root
          rm -rf $WORKSPACE $BOOT_IMG
