name: Find and Patch RC Files

on:
  workflow_dispatch:

jobs:
  find-and-patch:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find and Patch setenforce 1
        run: |
          echo "--- Searching for .rc files containing 'setenforce 1' ---"
          
          # Find all .rc files, show which ones contain the string, then patch them
          RC_FILES=$(grep -lr "setenforce 1" --include="*.rc" .)
          
          if [ -z "$RC_FILES" ]; then
            echo "✅ No .rc files with 'setenforce 1' found. Nothing to patch."
            exit 0
          fi
          
          echo "Found the following files to patch:"
          echo "$RC_FILES"
          
          # Use xargs to run sed on all found files
          echo "$RC_FILES" | xargs -I {} sed -i 's/setenforce 1/setenforce 0/g' {}
          
          echo "--- Verifying patches ---"
          # This will fail if any file still contains 'setenforce 1'
          if grep -lr "setenforce 1" --include="*.rc" .; then
            echo "::error:: Patching failed! 'setenforce 1' still found in some files."
            exit 1
          else
            echo "✅ SUCCESS: All instances of 'setenforce 1' have been replaced with 'setenforce 0'."
          fi
          
          echo "IMPORTANT: You must now commit these changes to your repository!"

      - name: Create Pull Request with Patched Files
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated patch: Force permissive in ramdisk RC files"
          title: "Automated Patch: Force Permissive"
          body: |
            This PR was automatically created by a GitHub Action.
            It finds all instances of `setenforce 1` in `.rc` files and replaces them with `setenforce 0` to ensure a permissive build.
          branch: "automated-permissive-patch"
          delete-branch: true

