name: Test Find and Patch RC Files

on:
  workflow_dispatch:

jobs:
  test-find-and-patch:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find and Patch setenforce 1
        run: |
          echo "--- Starting Test: Searching for and patching 'setenforce 1' in source .rc files ---"
          
          # Find all .rc files anywhere in the project that contain "setenforce 1"
          RC_FILES=$(grep -lr "setenforce 1" --include="*.rc" .)
          
          if [ -z "$RC_FILES" ]; then
            echo "✅ SUCCESS: No .rc files with 'setenforce 1' were found. This means either they don't exist or they are already permissive."
            exit 0
          fi
          
          echo "Found the following files to patch:"
          echo "$RC_FILES"
          
          # Use xargs to run sed on all found files
          echo "$RC_FILES" | xargs -I {} sed -i 's/setenforce 1/setenforce 0/g' {}
          
          echo "--- Verifying that the patch was successful ---"
          # This command will search again. If it finds anything, it means the patch failed.
          if grep -lr "setenforce 1" --include="*.rc" .; then
            echo "::error:: PATCH FAILED! 'setenforce 1' is still found in some files."
            exit 1
          else
            echo "✅ SUCCESS: All found instances of 'setenforce 1' have been replaced with 'setenforce 0'."
          fi
